### ISSUE TITLE
Selection of multiple rows / columns is not working when selecting the rows / columns via clicking and dragging the header

### ISSUE THREAD

**Issue by miteshyugtia** [Mobius1/Selectable#13]
Selection of multiple rows / columns is not working when selecting the rows / columns via clicking and dragging the header

**Comment by miteshyugtia** [comment]
Any updates or any possibility for this issue?

**Comment by Mobius1** [comment]
I'm not sure I understand. Are you using this on a HTML table?

**Comment by miteshyugtia** [comment]
Yes i am using Html table.
![table](https://user-images.githubusercontent.com/27283444/39811388-193cbb10-53a6-11e8-842c-e01f120b2c77.png)

**Comment by Mobius1** [comment]
That functionality isn't built in, but it can be easily implemented: https://codepen.io/Mobius1/pen/jamBzV/
