### ISSUE TITLE
It works with AngularJS?

### ISSUE THREAD

**Issue by dev15seucondominio** [Mobius1/Selectable#16]
Hi, i'm i really insterested into in use this gadget on a project but i need that it works on angular, when i try to do a ng-repeat Selectable stops to work. here an example:

whit ng-repeat: https://codepen.io/dev15/pen/MBQobQ?editors=1111

whitout: https://codepen.io/anon/pen/ejrBrJ?editors=1111

**Comment by Mobius1** [comment]
I'm not familiar with Angular so I can't help, sorry.

**Comment by mg1075** [comment]
@dev15seucondominio The DOM for the table rows in `ng-repeat` are not recognized when the selectable plugin is called. Similar issue described here: https://stackoverflow.com/questions/36682853/angular-directives-link-function-wont-manipulate-dom

Try running your codepen sample with this modification to your angularjs code.

```
var app = angular.module("app", []);

app.controller("myCtrl", function($scope, $timeout) {
        $scope.list = [1,2,3,4];
	
        var timerSelectable;

        timerSelectable = $timeout(function () {
             var selectable = new Selectable();
        }, 0);
	
        $scope.$on('$destroy', function () {
              timerSelectable.cancel();
        });
});
```
