### ISSUE TITLE
After Chrome update plugin doesn't work on touch devices. 

### ISSUE THREAD

**Issue by AlexandrTuniev** [Mobius1/Selectable#3]
Chrome v: 64.0.3282.140 
On touch  plugin throws an error 
Uncaught TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite.   at Selectable.end (selectable.js:705)
![2018-02-02_1801](https://user-images.githubusercontent.com/7453199/35736907-2afa36ce-0843-11e8-83d8-0acd52c45ef7.png)

**Comment by Mobius1** [comment]
The `touchend` check was missing from the `end()` method so the `pageX and `pageY` values passed to `elementFromPoint()` were invalid. It should be fixed now.

**Comment by AlexandrTuniev** [comment]
Hi, thanks for quick response, but unfortunately issue didn't fixed,  now that evt is undefined as e.touches is empty array. I have tried locally  evt = e.type === "touchend" ? e.touches[0] || e.changedTouches[0] : e;  and seems it works, however not sure if that is correct fix. 

![untitled](https://user-images.githubusercontent.com/7453199/35766878-d27319b4-08f9-11e8-966c-9861ea4c120c.png)
![2018-02-03_1603](https://user-images.githubusercontent.com/7453199/35766955-d01fe9ce-08fb-11e8-8bd2-2514b025bb65.png)

**Comment by AlexandrTuniev** [comment]
btw, as you may notice there is also an error in console related 'removeEventListener'.

**Comment by Mobius1** [comment]
I've pushed a quick fix until I can work on it properly on Monday. 👍
