### ISSUE TITLE
Scrolling not re-enabled after destroying Selectable on touch devices

### ISSUE THREAD

**Issue by mkucej** [Mobius1/Selectable#33]
Demonstrated here:
https://jsbin.com/gacakorobo/edit?output

1. Open on a phone.
2. Scroll the `#outer-div` up and down &mdash; works fine.
3. Init selectable. Selecting works as expected.
4. Destroy selectable. Scrolling the `#outer-div` is no longer possible.

I tried to fix this by adding a namespace to all events in Selectable, but that did not work. Then I nulled `this.events` in the `destroy()` method and that worked:

```JS
destroy: function() {
    this.disable();
    this.listeners = false;
    this.clear();
    this.state("clear");
    this.remove(this.items);
    this.events = null;
},
```

**Comment by w8less** [comment]
have the same problem
