### ISSUE TITLE
License problems

### ISSUE THREAD

**Issue by WWWuschel** [Mobius1/Selectable#37]
Unfortunately, there are several licenses within the repository. 

In the **readme.md** under Copyright at the bottom is **_BSD & MIT_**, in the file **LICENCE** is **_MIT_** and in the source code in **selectable.js** is **_Dual Licence MIT and GPL_**. 

What is the license under which the project may be used?

I suppose it is MIT and the others may be old remnants. I would be very grateful if it was clear under which license I am allowed to use the project!

**Comment by Mobius1** [comment]
It should be MIT. I must have been too idle to write the comments in the files and just copy / pasted from another of my repos. Fixed in `0.17.6`.
