### ISSUE TITLE
Question: "selecting" event, next to "selecteditem" and "deselecteditem" ?

### ISSUE THREAD

**Issue by chrimez** [Mobius1/Selectable#63]
Hi. I am working on replacing jQuery-ui, which offers [7 relevant events](https://api.jqueryui.com/selectable/), among them "selecting", "unselecting".
If I understood correctly, "Selectable" 0.19.1 does set respective classes (for formatting/display) "ui-selecting" when transitioning to "ui-selected", but it seems respective ["selecting" event](https://mobius1.github.io/Selectable/events.html)  is not provided. Is that understanding correct?

**Comment by Mobius1** [comment]
I need to update the docs as they're outdated. There isn't currently a "selecting" event, but I can add it in for the next release.

**Comment by chrimez** [comment]
Great - I considered various options to work around it. And I think it would make sense to include it. E.g. I figured no easy and straight forward ways to identify selecting an already selected item again - cause when "slectedItem" is triggered, any element is selected already.

Note I think it can make best sense to include both: selecting and un/deselecting .

**Comment by chrimez** [comment]
Perfect - thanks a lot :D
