### ISSUE TITLE
cdn.jsdelivr.net :  how to hand-pick a version?

### ISSUE THREAD

**Issue by chrimez** [Mobius1/Selectable#65]
Could not find [what link to use](https://mobius-studios.gitbook.io/selectable/getting-started/install) to self-select a specific Selectable release, e.g. 0.19.1 .

I only found this link:  [https://cdn.jsdelivr.net/npm/selectable.js@latest/selectable.min.js](https://cdn.jsdelivr.net/npm/selectable.js@latest/selectable.min.js) which points to latest release version.

By-the-way: is there a link to previous versions of the documentation (e.g. of the 0.19.1 release?)

**Comment by Mobius1** [comment]
Replace `latest` with the version number you require.
